services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend:latest
    command: ["osrm-routed", "--algorithm", "mld", "/data/peru.osrm"]
    ports:
      - "5000:5000"
    volumes:
      - ./routing/osrm:/data
